### ISSUE TITLE
Сделать кнопку "Спрятать разметку"

### ISSUE THREAD

**Issue by mit-idv** [TruePositiveLab/knotmarker#9]
Если мы рисуем разметку прямо по контуру дефекта, то его становится не разглядеть под этим контуром. Вот уже и не понять, сросшийся сучок или несросшийся. 

Нужно сделать кнопку. Пока её держишь - видишь картинку без разметки. Отпускаешь - разметка снова появляется. Так можно будет разглядеть оригинальную картинку, чтобы подкорректировать класс или контур.

**Comment by 4eBelka** [comment]
От выделенного дефекта остаются точки. Нужно прятать все
![image](https://cloud.githubusercontent.com/assets/10761218/18544716/a41c5c78-7b3e-11e6-97ba-f3e989c546ff.png)
